[book]
title = "<ceb/> ~ Custom Element Builder"
authors = ["Thibault Morin"]
description = "The book presents the usage of the ceb library."
language = "en"
src = "book"

[build]
build-dir = "public"

[output.html]
git-repository-url = "https://github.com/tmorin/ceb/"
git-repository-icon = "fa-github"

[output.html.search]
enable = true
