name: Continous Integration - Build

on: [ push, pull_request ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@tmorin'
      - name: Update apt
        run: sudo apt-get update
      - name: Install apt dependencies
        run: sudo apt-get install -y xvfb firefox chromium-browser
      - name: Install mdbook
        run: wget https://github.com/rust-lang/mdBook/releases/download/v${MDBOOK_VERSION}/mdbook-v${MDBOOK_VERSION}-x86_64-unknown-linux-gnu.tar.gz -O - | tar -xz -C /tmp
        env:
          MDBOOK_VERSION: '0.4.14'
      - name: Install dependencies
        run: npm ci
      - name: Bootstrap lerna
        run: npm run bootstrap
      - name: Build package
        run: npm run build
      - name: lint package
        run: npm run lint
      - name: Test package
        run: |
          export DISPLAY=':99.0'
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          npm test
        env:
          CHROME_BIN: '/usr/bin/chromium-browser'
      - name: Build book
        run: /tmp/mdbook clean && /tmp/mdbook build
      - name: Build typedoc
        run: npm run doc:typedoc
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
      - name: Publish package
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: npm run release:publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish documentation
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
